name: Delete All Releases and Tags

on:
  workflow_dispatch:   # 手动触发

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all releases and tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching releases from ${{ github.repository }}"

          releases=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            | jq -r '.[] | [.id, .tag_name] | @tsv')

          if [ -z "$releases" ]; then
            echo "⚠️ No releases found."
            exit 0
          fi

          while IFS=$'\t' read -r id tag; do
            echo "Deleting release ID=$id TAG=$tag"

            # 删除 release
            curl -s -X DELETE -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/releases/$id

            # 删除远程 tag
            curl -s -X DELETE -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$tag
          done <<< "$releases"

          echo "✅ All releases and tags deleted."
